app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/views/devise/sessions/new.html.erb, app/views/users/show.html.erb, config/application.rb
sign in時のflash message実装。
ログイン時にmy pageにて「ログインしました」とflashを表示。
BootstrapにてCSSを当てた。
sign in画面でのflash messageだけ日本語化が出来なかった。
=> sign in時のflash message実装

app/controllers/users_controller.rb, app/views/users/show.html.erb
mypageでの本日以降の予約状況の表示を改修した。
コントローラーにてwhereメソッドを使用し本日以降の予約データを取得した。
=> mypage予約状況（本日以降）の改修

app/models/store.rb, app/models/studio.rb, db/migrate/20180626135051_create_stores.rb, db/migrate/20180626135130_create_studios.rb, db/schema.rb, test/fixtures/stores.yml, test/fixtures/studios.yml, test/models/store_test.rb, test/models/studio_test.rb
=> Store、Studioテーブルの作成

app/controllers/stores_controller.rb, config/routes.rb
Storeモデルのルーティング、コントローラーを作成しました。
・indexアクション及びviewは店舗の一覧を表示予定
・newアクション及びviewは店舗の登録フォームを作成予定
・showアクション及びviewは各店舗の詳細ページを作成予定（予約状況の確認、Studioの登録フォームへのリンク、Studioの削除ボタン）
上記ページは管理人のみアクセス出来るようにする予定です。
=> Storeモデルのルーティング、コントローラーの作成

app/assets/stylesheets/custom.css.scss, app/controllers/stores_controller.rb, app/views/stores/index.html.erb, app/views/stores/new.html.erb
Storeテーブルへの店舗登録フォームを作成しました。
・form_forを使用したviewの作成（/stores/new）
・Storesコントローラーにて登録が出来るようにアクションを記載
viewにて入力を行い登録ボタンを押すとindex.html.erb（店舗一覧画面）に飛ぶように設定しました。
店舗一覧画面はまだ未作成ですので今後branchを切って作成予定です。
=> 店舗の登録フォームの作成

app/assets/stylesheets/custom.css.scss, app/controllers/stores_controller.rb, app/views/stores/index.html.erb
店舗の一覧画面をtableタグを使用して作成しました。
店舗詳細ボタン、店舗削除ボタンも実装。
店舗詳細ボタンに関しましては店舗のshowページに移動し店舗の予約状況の確認、スタジオの登録のページに行けるようにする予定です。
=> #35 店舗一覧画面の作成

app/controllers/stores_controller.rb, app/views/stores/index.html.erb, app/views/stores/show.html.erb
店舗の個別ページのレイアウトを作成しました。
スタジオの予約状況のボタン、スタジオ削除ボタン、スタジオの新規登録ボタンを配置しました。
各ボタンの機能実装につきましては別でブランチを切って開発する予定です。
=> #42 店舗の詳細ページの作成

app/controllers/registrations_controller.rb, app/views/devise/registrations/new.html.erb, db/migrate/20180708041550_add_admin_to_users.rb, db/schema.rb
adminカラムをUsersテーブルに追加しました。
また、sign upページにて一般会員、管理人のラジオボタンを作成しました。
=> adminカラムの作成、sign upページにラジオボタンの作成

app/controllers/reservations_controller.rb, app/controllers/stores_controller.rb, app/controllers/users_controller.rb
一般ユーザーのstoreページへアクセス制限をかけた。
Storesコントローラーにメソッドを定義し、current_userがadminかを判定しています。
=> #47 一般ユーザーのstoreページへのアクセス制限

app/assets/stylesheets/custom.css.scss, app/controllers/stores_controller.rb, app/controllers/studios_controller.rb, app/views/stores/show.html.erb, app/views/studios/new.html.erb, config/routes.rb
スタジオコントローラーの作成、スタジオのnew.html.erbにてスタジオの登録フォームのビューを作成しました。
スタジオテーブルに紐付くストアIDは店舗詳細画面から新規スタジオ登録ボタンを押す際にlink_toメソッドにてパラメーターを渡す仕様にしました。
スタジオ登録後は店舗詳細画面にリダイレクトします。
店舗詳細画面ではeach文を回し、スタジオの一覧が表示されます。
=> #29 スタジオの登録フォームの作成 

app/helpers/application_helper.rb, app/views/layouts/_header.html.erb, app/views/stores/index.html.erb
adminユーザーでのログイン時のみヘッダーに店舗登録（new_store_path）、店舗一覧（stores_path）のリンクを表示するように実装しました。また、ヘッダーパーシャルのインデントの記述も整えました。
店舗一覧（stores_path）のページから店舗IDを削除しました。
=> #33 管理人用のヘッダーを作成

app/controllers/stores_controller.rb, app/controllers/users_controller.rb
今まではReservationテーブル、Storeテーブルからデータを取得する際にfindメソッドを使用していたが、エラーが発生しました。最初はデータが0件のためのエラーかと思いましたが、それだけでなくそもそもの記載方法に問題があった。
データの取得の方法をWhereメソッドによる検索にしエラーは解消されました。
@reservation = Reservation.where('date >= ?', Date.today, user_id:@user.id)
上記のように条件を並べて記載するとエラーになったため以下のようにwhereを2つ並べて記載しました。
@reservation = Reservation.where('date >= ?', Date.today).where(user_id:@user.id)
=> #Reservationテーブル、Storeテーブルを一覧表示する際のエラーを解消

config/database.yml
=> #64 DB設定を修正

app/controllers/application_controller.rb, app/controllers/stores_controller.rb, app/controllers/studios_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_flash_messages.html.erb, app/views/stores/index.html.erb, app/views/stores/show.html.erb, config/routes.rb
以下の項目にflashメッセージを実装しました。レイアウトはBootstrapを使用しました。
・店舗登録時に店舗を追加しましたのメッセージ表示
・店舗削除時に店舗を削除しましたのメッセージ表示
・スタジオ登録時に店舗を追加しましたのメッセージ表示
・スタジオ削除時に店舗を削除しましたのメッセージ表示
=> #12 メッセージの実装①（店舗・スタジオ登録時）

README.md, db/seeds.rb
seeds.rbファイルにスタブを作成するコードを記載しました。
rake db:seedを実行することで以下のスタブが生成されます。
・User（一般ユーザーとadminユーザー）
・Store
・Studio
・Reservation
よろしくお願いします。
=> #76 seedファイルを使用してスタブの作成

app/views/users/show.html.erb
https://github.com/ecoyamas/msrs_app/issues/80
=> #80 【my page】リンク修正

app/assets/stylesheets/custom.css.scss, app/views/users/show.html.erb
https://github.com/ecoyamas/msrs_app/issues/84
=> #84 【メニューバー、my page】レイアウト修正

app/controllers/reservations_controller.rb, app/views/reservations/_form.html.erb, app/views/reservations/new.html.erb, app/views/studios/show.html.erb
https://github.com/ecoyamas/msrs_app/issues/72
【特記事項】
・reservationsコントローラーのnewアクションの @store = Store.find(@studio.store_id)は
@store = Store.find(@studio)ではエラーだったのでこの記載にしてます。
=> #72 【予約新規作成画面】予約新規作成画面 修正

app/views/layouts/_header.html.erb
https://github.com/ecoyamas/msrs_app/issues/88
=> #88 【メニューバー】Link削除 

app/controllers/stores_controller.rb
https://github.com/ecoyamas/msrs_app/issues/89
【特記事項】
以下の２点の修正が新たに必要かと思いました。
・店舗一覧画面のh1タグがList of storesとなっているのを日本語に修正
・店舗一覧画面の店舗削除ボタン、新規登録ボタンが一般ユーザーにも見えてしまっているので
　adminユーザーの時のみ表示に修正。
=> #89 【店舗一覧画面】admin以外だとルートにリダイレクトされるバグ

app/assets/stylesheets/custom.css.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
https://github.com/ecoyamas/msrs_app/issues/75
【特記事項】
・Sign up画面のflashメッセージのレイアウトが正常に当たっていませんが、その部分はtask70で修正する認識ですので修正しておりません。
=> #75 【Sign up画面とSign in画面】deviseのレイアウトをBootstrapに修正

app/views/stores/index.html.erb
https://github.com/ecoyamas/msrs_app/issues/92
=> #92 【店舗一覧画面】レイアウト修正 

db/migrate/20180823053734_add_start_datetime_to_reservations.rb, db/migrate/20180823053921_add_end_datetime_to_reservations.rb, db/migrate/20180823054351_remove_frame_to_.rb, db/migrate/20180823055126_remove_date_to_reservations.rb, db/migrate/20180823060033_add_end_date_to_reservations.rb, db/migrate/20180823060052_add_end_start_time_to_reservations.rb, db/migrate/20180823060103_add_end_end_time_to_reservations.rb, db/schema.rb
https://github.com/ecoyamas/msrs_app/issues/99
=> #99 frameカラム削除、start_datetime、end_datetimeカラム追加

app/assets/stylesheets/custom.css.scss, app/helpers/application_helper.rb, app/views/devise/sessions/new.html.erb, app/views/home/top.html.erb, app/views/shared/_flash_messages.html.erb, app/views/users/show.html.erb, config/locales/devise.ja.yml
https://github.com/ecoyamas/msrs_app/issues/70
=> #70 【Sign up、Sign in、Sign out】flashメッセージ実装

app/controllers/reservations_controller.rb, config/locales/devise.ja.yml
https://github.com/ecoyamas/msrs_app/issues/104
=> #104 【予約新規登録、予約編集】ご利用時間が存在しない場合のバリデーションエラーのメッセージ修正

app/controllers/reservations_controller.rb, app/views/reservations/_form.html.erb
https://github.com/ecoyamas/msrs_app/issues/106
【特記事項】
前回プッシュ時にカラムを変えてしまったので新たにローカルでtask106_1というブランチを切り作業しプッシュしました。
=> #106  【予約編集画面】ご利用時間のデータを取得
